version: '3'
services:
  filebeat:
    container_name: filebeat 
    image: docker.elastic.co/beats/filebeat:7.4.2
    volumes:
     - /opt/threathunt/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
     - /opt/zeek/logs/:/var/log/host/:ro
    networks: 
     - elastic
    command: filebeat -e -strict.perms=false
    restart: unless-stopped
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge
